### ISSUE TITLE
Locking file access

### ISSUE THREAD

**Issue by FilWisher** [guardian/gobby#2]
Should the file accesses in Save [0] and Load [1] be guarded by synchronization primitives?

I know file locking is also done by the kernel (depending on OS) but I'm not sure whether this could result in race conditions for file access. I can't find any hard evidence about whether ioutil's file access functions are concurrency-safe.

[0] https://github.com/guardian/gobby/blob/master/gobby.go#L89
[1] https://github.com/guardian/gobby/blob/master/gobby.go#L53

**Comment by FilWisher** [comment]
I just tested with this short program:

``` go
func write(f, s string) {
    for i := 0; i < 1000; i++{
        ioutil.WriteFile(f, []byte(s), 0644)
        fmt.Println("written ", s)
    }
}

func read(f string, ch chan<- interface{}) {
    for i := 0; i < 1000; i++ {
        d, err := ioutil.ReadFile(f)
        if err != nil {
            log.Fatal("read error: ", err.Error())
            ch <- true
        }
        fmt.Println("got: ", string(d))
    }
    ch <- true
}

func main() {
    ch := make(chan interface{})
    go write("hello.txt", "aaaaaaaaaa")
    go write("hello.txt", "bbbbbbbbbbbb")
    go read("hello.txt", ch)
    <-ch
}
```

From `read()`, we should only be able to see `got:`, `got: aaaaaaaaaa` or `got: bbbbbbbbbbbb` but I was able to grep these lines (in original sequence):

```
got: 
written  bbbbbbbbbbbb
got:  aaaaaaaaaabb
```

This isn't formal enough to be conclusive but its indicative that they aren't safe.

**Comment by kenoir** [comment]
Yes. I think so. The feedback is much appreciated. I'm out of the office for a couple of weeks but I'll make the change when I'm back.
